// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu0jO3BZvnwLgoEvef5tl87KbcgIKCMnQ',
    appId: '1:293645907712:web:4311f64ffef8f89d1665e5',
    messagingSenderId: '293645907712',
    projectId: 'taskassiment',
    authDomain: 'taskassiment.firebaseapp.com',
    storageBucket: 'taskassiment.appspot.com',
    measurementId: 'G-4F4QNQZJXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjcslRQWSprOzkRvOdxn_8L5FVZq5xN0g',
    appId: '1:293645907712:android:b2faead273a1eaa21665e5',
    messagingSenderId: '293645907712',
    projectId: 'taskassiment',
    storageBucket: 'taskassiment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALynNS8FkGH7D8jUR9ekhzkEtkMJy0jRw',
    appId: '1:293645907712:ios:1a4cff5affb7089e1665e5',
    messagingSenderId: '293645907712',
    projectId: 'taskassiment',
    storageBucket: 'taskassiment.appspot.com',
    iosClientId: '293645907712-m7kgsf8teahlnk25gi3de5buh293thog.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskassiment',
  );
}
